package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.CustomerTypeDO;
import com.sequarius.titan.sample.domain.CustomerTypeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    long countByExample(CustomerTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByExample(CustomerTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insert(CustomerTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insertSelective(CustomerTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    List<CustomerTypeDO> selectByExample(CustomerTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    CustomerTypeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerTypeDO record, @Param("example") CustomerTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") CustomerTypeDO record, @Param("example") CustomerTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKey(CustomerTypeDO record);
}