package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.CustomerLinkmanDO;
import com.sequarius.titan.sample.domain.CustomerLinkmanDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerLinkmanDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    long countByExample(CustomerLinkmanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByExample(CustomerLinkmanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insert(CustomerLinkmanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insertSelective(CustomerLinkmanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    List<CustomerLinkmanDO> selectByExample(CustomerLinkmanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    CustomerLinkmanDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerLinkmanDO record, @Param("example") CustomerLinkmanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") CustomerLinkmanDO record, @Param("example") CustomerLinkmanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerLinkmanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_linkman
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKey(CustomerLinkmanDO record);
}