package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.CustomerDeliveryAddressDO;
import com.sequarius.titan.sample.domain.CustomerDeliveryAddressDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerDeliveryAddressDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    long countByExample(CustomerDeliveryAddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByExample(CustomerDeliveryAddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insert(CustomerDeliveryAddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insertSelective(CustomerDeliveryAddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    List<CustomerDeliveryAddressDO> selectByExample(CustomerDeliveryAddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    CustomerDeliveryAddressDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerDeliveryAddressDO record, @Param("example") CustomerDeliveryAddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") CustomerDeliveryAddressDO record, @Param("example") CustomerDeliveryAddressDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerDeliveryAddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_delivery_address
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKey(CustomerDeliveryAddressDO record);
}