package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.CustomerDO;
import com.sequarius.titan.sample.domain.CustomerDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    long countByExample(CustomerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByExample(CustomerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insert(CustomerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insertSelective(CustomerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    List<CustomerDO> selectByExample(CustomerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    CustomerDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerDO record, @Param("example") CustomerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") CustomerDO record, @Param("example") CustomerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKey(CustomerDO record);
}