package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.CustomerFinanceDO;
import com.sequarius.titan.sample.domain.CustomerFinanceDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerFinanceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    long countByExample(CustomerFinanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByExample(CustomerFinanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insert(CustomerFinanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insertSelective(CustomerFinanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    List<CustomerFinanceDO> selectByExample(CustomerFinanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    CustomerFinanceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerFinanceDO record, @Param("example") CustomerFinanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") CustomerFinanceDO record, @Param("example") CustomerFinanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerFinanceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_finance
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKey(CustomerFinanceDO record);
}