package com.sequarius.titan.sample.repository;

import com.sequarius.titan.sample.domain.TradingCurrencyDO;
import com.sequarius.titan.sample.domain.TradingCurrencyDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TradingCurrencyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    long countByExample(TradingCurrencyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByExample(TradingCurrencyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insert(TradingCurrencyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int insertSelective(TradingCurrencyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    List<TradingCurrencyDO> selectByExample(TradingCurrencyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    TradingCurrencyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") TradingCurrencyDO record, @Param("example") TradingCurrencyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByExample(@Param("record") TradingCurrencyDO record, @Param("example") TradingCurrencyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(TradingCurrencyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trading_currency
     *
     * @mbg.generated Mon Feb 17 15:26:31 CST 2020
     */
    int updateByPrimaryKey(TradingCurrencyDO record);
}